#!/bin/bash
# Script pour pousser le site XR1 sur GitHub Pages
# Usage: ./deploy-to-github.sh <username>

USERNAME=${1:-structurexr1}
REPO_NAME="xr1-site"

echo "🚀 Déploiement XR1 Site sur GitHub Pages"
echo "========================================="
echo ""
echo "Étapes à suivre:"
echo ""
echo "1. Créer le repo sur GitHub:"
echo "   https://github.com/new"
echo "   - Nom: $REPO_NAME"
echo "   - Public"
echo "   - Ne PAS initialiser avec README (déjà présent)"
echo ""
echo "2. Configurer le remote et pousser:"
echo "   git remote add origin https://github.com/$USERNAME/$REPO_NAME.git"
echo "   git branch -M main"
echo "   git push -u origin main"
echo ""
echo "3. Activer GitHub Pages:"
echo "   - Aller sur https://github.com/$USERNAME/$REPO_NAME/settings/pages"
echo "   - Source: GitHub Actions"
echo ""
echo "4. Attendre le déploiement (2-3 minutes)"
echo ""
echo "5. Accéder au site:"
echo "   https://$USERNAME.github.io/$REPO_NAME/"
echo ""
echo "========================================="
echo ""
echo "Commandes copiables:"
echo "--------------------"
echo "git remote add origin https://github.com/$USERNAME/$REPO_NAME.git"
echo "git branch -M main"
echo "git push -u origin main"
